const mongoose = require('mongoose');
const { CATEGORIES } = require('../constants/categories.constant');

const TopicSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    slug: { type: String, unique: true, lowercase: true },
    description: String,
    category: { type: String, enum: CATEGORIES },

    // Keywords for auto-matching articles to this topic
    keywords: [{ type: String, lowercase: true }],
    entities: {
      people: [String],
      organizations: [String],
      locations: [String],
    },

    image: { url: String, key: String },
    coverColor: String,

    followerCount: { type: Number, default: 0 },
    articleCount: { type: Number, default: 0 },

    isActive: { type: Boolean, default: true },
    isTrending: { type: Boolean, default: false },
    trendingScore: { type: Number, default: 0 },

    // Auto-generated by AI or manually curated by editors
    type: { type: String, enum: ['auto', 'curated'], default: 'auto' },
    curatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

    // Related topics
    relatedTopics: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Topic' }],

    // Last time an article was added to this topic
    lastArticleAt: Date,
  },
  { timestamps: true }
);

TopicSchema.index({ slug: 1 }, { unique: true });
TopicSchema.index({ keywords: 1 });
TopicSchema.index({ isTrending: 1, trendingScore: -1 });
TopicSchema.index({ category: 1, isActive: 1 });
TopicSchema.index({ isActive: 1, articleCount: -1 });
TopicSchema.index({ name: 'text', keywords: 'text' });

TopicSchema.pre('save', function (next) {
  if (this.isModified('name') && !this.slug) {
    this.slug = this.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  }
  next();
});

TopicSchema.statics.getTrending = function (limit = 10) {
  return this.find({ isActive: true, isTrending: true })
    .sort({ trendingScore: -1 })
    .limit(limit)
    .lean();
};

TopicSchema.statics.findByKeyword = function (keyword) {
  return this.find({
    isActive: true,
    keywords: { $regex: keyword, $options: 'i' },
  }).lean();
};

module.exports = mongoose.model('Topic', TopicSchema);